// Copyright (c) 2026 Jeremy Ellis and contributors
//
// CodeBrix.LilyPort is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using Lily.Docs;
using Lily.Docs.Generation;
using SilverAssertions;
using Xunit;

namespace Lily.Docs.Tests;

/// <summary>
/// The corpus mirror under <c>Documentation/</c> is an INPUT, and these gates are about it
/// still being the input it was recorded as (decision D49(b), ruled 2026-08-18).
/// </summary>
public sealed class CorpusMirrorTests
{
    /// <summary>The mirror holds none of the ports nineteen generated outputs.</summary>
    [Fact]
    public void the_mirror_holds_none_of_the_ports_nineteen_generated_outputs()
    {
        //Arrange
        HashSet<string> generated = new HashSet<string>(
            DocumentationGenerator.ExpectedOutputs, StringComparer.Ordinal);

        //Act
        List<string> found = Directory
            .EnumerateFiles(ToolPaths.CorpusDirectory, "*", SearchOption.AllDirectories)
            .Where(path => generated.Contains(Path.GetFileName(path)))
            .ToList();

        //Assert
        // ⚠ THIS IS THE ASSUMPTION "THE GENERATED BYTES ARE THE SPECIFICATION" ACTUALLY
        // RESTS ON, and it is not the search-path order. The Texinfo package searches the
        // source file's own directory and that directory's PARENT before anything the
        // caller supplies, which for a corpus manual means Documentation/en and
        // Documentation come first. If a re-sync ever copied one of the port's nineteen
        // outputs into the mirror, the corpus copy would win silently and the manual would
        // be rendered from upstream's build product instead of from the port's — with no
        // warning, because a resolved include is not an event.
        //
        // They are absent for the same reason they are absent upstream: they are build
        // products there too.
        found.Should().BeEmpty();
        generated.Count.Should().Be(19);
    }

    /// <summary>Every mirrored file matches the recorded manifest.</summary>
    [Fact]
    public void every_mirrored_file_matches_the_recorded_manifest()
    {
        //Arrange
        string manifestPath = Path.Combine(ToolPaths.CorpusDirectory, "MANIFEST.sha256");
        Dictionary<string, string> recorded = ReadManifest(manifestPath);

        //Act
        List<string> wrong = new List<string>();
        foreach (KeyValuePair<string, string> entry in recorded)
        {
            string path = Path.Combine(ToolPaths.CorpusDirectory, entry.Key);
            if (!File.Exists(path))
            {
                wrong.Add(entry.Key + ": absent");
                continue;
            }

            if (!string.Equals(Sha256Of(path), entry.Value, StringComparison.Ordinal))
            {
                wrong.Add(entry.Key + ": content changed");
            }
        }

        //Assert
        // The mirror's README says NEVER EDIT ANYTHING IN THIS DIRECTORY, and this is what
        // makes that a checked claim rather than a request. Every expected-warnings baseline
        // in this tool is frozen against these exact bytes: an edited input changes what a
        // manual MEANS, and would show up as a baseline that "needed" re-freezing.
        wrong.Should().BeEmpty();
        // 636 at wave LD3: the 633 D49(b) copied in, plus the three pictures this wave
        // found — two @sourceimage targets and one \epsfile target named from inside a
        // music snippet.
        recorded.Count.Should().Be(636);
    }

    /// <summary>The manifest names every file in the mirror.</summary>
    [Fact]
    public void the_manifest_names_every_file_in_the_mirror()
    {
        //Arrange
        string manifestPath = Path.Combine(ToolPaths.CorpusDirectory, "MANIFEST.sha256");
        HashSet<string> recorded = new HashSet<string>(
            ReadManifest(manifestPath).Keys, StringComparer.Ordinal);

        //Act
        // The manifest and the README describe themselves rather than being described, so
        // they are the two files it does not list.
        List<string> unlisted = Directory
            .EnumerateFiles(ToolPaths.CorpusDirectory, "*", SearchOption.AllDirectories)
            .Select(path => Path.GetRelativePath(ToolPaths.CorpusDirectory, path)
                .Replace(Path.DirectorySeparatorChar, '/'))
            .Where(relative => relative != "MANIFEST.sha256" && relative != "README.txt")
            .Where(relative => !recorded.Contains(relative))
            .ToList();

        //Assert
        // The paired half of the gate above. Checking recorded files against disk catches an
        // edit; checking disk against the record catches an ADDITION — a file copied in
        // without its provenance being written down, which is how a GFDL tree stops being
        // one that can be accounted for.
        unlisted.Should().BeEmpty();
    }

    private static Dictionary<string, string> ReadManifest(string path)
    {
        Dictionary<string, string> entries = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (string line in File.ReadAllLines(path))
        {
            int separator = line.IndexOf("  ", StringComparison.Ordinal);
            if (separator > 0)
            {
                entries[line.Substring(separator + 2)] = line.Substring(0, separator);
            }
        }

        return entries;
    }

    private static string Sha256Of(string path)
    {
        using FileStream stream = File.OpenRead(path);
        return Convert.ToHexStringLower(SHA256.HashData(stream));
    }
}
