// Copyright (c) 2026 Jeremy Ellis and contributors
//
// CodeBrix.LilyPort is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using CodeBrix.PdfDocCreate.Html2Pdf;
using CodeBrix.Texinfo2Html;
using Lily.Docs;
using Lily.Docs.Generation;
using Lily.Docs.Rendering;
using Lily.Docs.Snippets;
using SilverAssertions;
using Xunit;

namespace Lily.Docs.Tests;

/// <summary>
/// The wave-LD3 gates: the Notation Reference renders to HTML from the port's own generated
/// appendices and the mirrored corpus prose, with its music engraved by the port's own
/// engine.
/// </summary>
public sealed class NotationReferenceRenderTests : IClassFixture<NotationReferenceFixture>
{
    /// <summary>
    /// One marker per generated fragment: a string that appears in THAT fragment's bytes and
    /// in none of the other seventeen, so finding it in the rendered HTML says which file
    /// arrived rather than only that something did.
    /// <para>
    /// Chosen by hand and then CHECKED —
    /// <see cref="each_marker_is_unique_to_its_own_generated_fragment"/> recomputes the
    /// uniqueness from the generated bytes every run, so a generation change that made a
    /// marker ambiguous fails there rather than weakening this gate silently.
    /// </para>
    /// <para>
    /// ⚠ <c>hyphenation.itexi</c> has no entry because it produces NO visible output: it is a
    /// list of TeX hyphenation points. That it resolved is covered by the include-warning
    /// gate instead, which is exactly why that gate needs its own control.
    /// </para>
    /// <para>
    /// ⚠ The two <c>break-align-*</c> fragments are permutations of ONE table — the same
    /// grob and symbol names in both — so no single name can separate them. Their markers are
    /// the column headings, which is the one place the two documents differ in words.
    /// </para>
    /// </summary>
    private static readonly Dictionary<string, string> FragmentMarkers =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "break-align-grobs-by-symbols.tely", "used by grob(s)" },
            { "break-align-symbols-by-grobs.tely", "break-align symbol(s)" },
            { "context-mod-identifiers.tely", "RemoveAllEmptyStaves" },
            { "css-colors.tely", "crimson" },
            { "identifiers.tely", "Accidental.color" },
            { "markup-commands.tely", "StandaloneRhythmScore" },
            { "markup-list-commands.tely", "point-stencil" },
            { "outside-staff-priorities.tely", "BassFigureAlignmentPositioning" },
            { "paper-sizes.tely", "Australia" },
            { "paper-variables.tely", "auto-first-page-number" },
            { "script-priorities.tely", "AccidentalPlacement" },
            { "standard-colors.tely", "darkyellow" },
            { "type-predicates.tely", "Pango" },
            { "universal-colors.tely", "bluegreen" },
            { "x11-colorN.tely", "antiquewhite1" },
            { "x11-grayN.tely", "gray100" },
            { "x11-unnumbered-colors.tely", "navyblue" },
        };

    /// <summary>
    /// The seven music symbols this manual carries: ♭ ♮ ♯ 𝄪 𝄫 𝄴 𝄵 — three from the Basic
    /// Multilingual Plane and four from the Supplementary Plane.
    /// <para>
    /// ⚠ MEASURED 2026-08-19, AND IT CORRECTS THE PHASE PLAN: they are not prose. All seven
    /// occur inside ONE <c>@lilypond[quote]</c> snippet in the port's own generated
    /// <c>markup-commands.tely</c>, where they are LilyPond markup — <c>\tiny \number ♭</c>
    /// — in a table of Unicode accidental glyphs. The snippet is not <c>verbatim</c>, so its
    /// source is never shown; the seven reach the reader as ENGRAVED MUSIC, drawn by the
    /// port's own engine into an SVG, and no character of them is ever handed to a text
    /// renderer.
    /// </para>
    /// <para>
    /// This matters beyond this gate. Decision D50 is about the seven having no covering font
    /// in the Html2Pdf chain — a question that only arises for text Html2Pdf must SET. On the
    /// same measurement <c>changes.tely</c>'s 𝄴 𝄵 are also inside a <c>@lilypond</c> snippet,
    /// and only <c>music-glossary.tely</c> carries any of them as prose: ♭ four times and ♯
    /// once, in a chord-name multitable. So D50's real footprint is one manual and two
    /// characters, and it is wave LD5's manual rather than this one's or LD4's. The ruling
    /// is Jeremy's; the measurement is recorded here because it is where it was made.
    /// </para>
    /// </summary>
    private const string MusicSymbols = "♭♮♯\U0001d12a\U0001d12b\U0001d134\U0001d135";

    private readonly NotationReferenceFixture _fixture;

    /// <summary>Creates the test class over the shared render.</summary>
    /// <param name="fixture">The one generation-and-render run.</param>
    public NotationReferenceRenderTests(NotationReferenceFixture fixture)
    {
        _fixture = fixture;
    }

    /// <summary>Html render warnings match the frozen baseline exactly.</summary>
    [Fact]
    public void html_render_warnings_match_the_frozen_baseline_exactly()
    {
        //Arrange
        string baselinePath = Path.Combine(
            ToolPaths.ExpectedWarningsDirectory, _fixture.Manual.Name + ".tsv");
        SortedDictionary<string, int> expected = WarningSummary.ReadBaseline(baselinePath);

        //Act
        SortedDictionary<string, int> actual = WarningSummary.Count(_fixture.Html.Warnings);

        //Assert
        // Both directions, as everywhere in this suite: a category that shrank is as much a
        // change to look at as one that grew.
        actual.Should().BeEquivalentTo(expected, Report(_fixture.Html.Warnings));
    }

    /// <summary>Html render produces no include warnings.</summary>
    [Fact]
    public void html_render_produces_no_include_warnings()
    {
        //Arrange
        IReadOnlyList<string> warnings = _fixture.Html.Warnings;

        //Act
        List<string> includeWarnings = warnings
            .Where(w => WarningSummary.CategoryOf(w) == "Include").ToList();

        //Assert
        // ⚠ THIS ZERO IS ONLY MEANINGFUL BESIDE ITS CONTROL. A warning channel that had
        // stopped reporting would produce the same zero. IncludeWarningControlTests renders a
        // document with thirty-nine knowably-absent includes in the same suite and asserts
        // exactly thirty-nine, which is what separates the two readings.
        //
        // What the zero says: every one of this manual's includes resolved — the corpus
        // prose, the vendored GFDL macros, the version stand-in, AND the eighteen files the
        // port generated. The Texinfo repository's own gate carries
        // hasBuildGeneratedIncludes: true for this manual because those eighteen are absent
        // there; here they are supplied from the port's own run, so it flips to false.
        includeWarnings.Should().BeEmpty();
    }

    /// <summary>Html render produces no unresolved reference warnings.</summary>
    [Fact]
    public void html_render_produces_no_unresolved_reference_warnings()
    {
        //Arrange
        IReadOnlyList<string> warnings = _fixture.Html.Warnings;

        //Act
        List<string> referenceWarnings = warnings
            .Where(w => WarningSummary.CategoryOf(w) == "Reference").ToList();

        //Assert
        // The Texinfo repository's own notation baseline tolerated one aggregated Reference
        // warning covering "24 refs into build-generated markup-commands.tely etc." Those
        // targets are supplied here, so this is zero — the same manual, rendered whole
        // because the port produced the parts upstream's build produces.
        referenceWarnings.Should().BeEmpty();
    }

    /// <summary>Every internal link in the html points at an id that exists.</summary>
    [Fact]
    public void every_internal_link_in_the_html_points_at_an_id_that_exists()
    {
        //Arrange
        string html = _fixture.HtmlText;
        HashSet<string> ids = new HashSet<string>(
            Regex.Matches(html, "id=\"([^\"]+)\"").Select(m => m.Groups[1].Value));

        //Act
        List<string> targets = Regex.Matches(html, "href=\"#([^\"]+)\"")
            .Select(m => m.Groups[1].Value).Distinct().ToList();
        List<string> dangling = targets.Where(t => !ids.Contains(t)).ToList();

        //Assert
        // The strongest structural claim available with no fidelity target: not "the render
        // finished" but "every link it wrote goes somewhere". Many of these cross from the
        // corpus prose INTO the port's generated appendices, which is the join this wave is
        // about.
        dangling.Should().BeEmpty();
        targets.Count.Should().BeGreaterThan(1000);
        ids.Count.Should().BeGreaterThan(1000);
    }

    /// <summary>Each marker is unique to its own generated fragment.</summary>
    [Fact]
    public void each_marker_is_unique_to_its_own_generated_fragment()
    {
        //Arrange
        Dictionary<string, string> texts = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (string name in DocumentationGenerator.ExpectedOutputs)
        {
            if (name != "internals.texi")
            {
                texts[name] = File.ReadAllText(
                    Path.Combine(_fixture.GeneratedDirectory, name));
            }
        }

        //Act
        List<string> ambiguous = new List<string>();
        foreach (KeyValuePair<string, string> marker in FragmentMarkers)
        {
            List<string> holders = texts
                .Where(entry => entry.Value.Contains(marker.Value, StringComparison.Ordinal))
                .Select(entry => entry.Key).ToList();
            if (holders.Count != 1 || holders[0] != marker.Key)
            {
                ambiguous.Add(marker.Value + " -> " + string.Join(", ", holders));
            }
        }

        //Assert
        // Recomputed from the bytes every run rather than trusted. A marker that stopped
        // being unique would turn the gate below into "some fragment arrived", and it would
        // do it silently.
        ambiguous.Should().BeEmpty();
        texts.Count.Should().Be(18);
        FragmentMarkers.Count.Should().Be(17);
    }

    /// <summary>Every generated fragment reached the rendered document.</summary>
    [Fact]
    public void every_generated_fragment_reached_the_rendered_document()
    {
        //Arrange
        string html = _fixture.HtmlText;

        //Act
        List<string> missing = FragmentMarkers
            .Where(marker => !html.Contains(marker.Value, StringComparison.Ordinal))
            .Select(marker => marker.Key)
            .ToList();

        //Assert
        // THE WAVE'S OWN CLAIM, stated as content rather than as an absence of warnings:
        // seventeen of the eighteen files the port generated are visibly IN the manual. The
        // eighteenth, hyphenation.itexi, renders nothing by design and is covered by the
        // include-warning gate.
        missing.Should().BeEmpty();
    }

    /// <summary>The manual includes all eighteen generated fragments by name.</summary>
    [Fact]
    public void the_manual_includes_all_eighteen_generated_fragments_by_name()
    {
        //Arrange
        List<string> fragments = DocumentationGenerator.ExpectedOutputs
            .Where(name => name != "internals.texi").ToList();
        string sources = string.Join("\n", Directory
            .EnumerateFiles(Path.Combine(ToolPaths.CorpusDirectory, "en"), "*.ite*",
                SearchOption.AllDirectories)
            .Concat(Directory.EnumerateFiles(Path.Combine(ToolPaths.CorpusDirectory, "en"),
                "*.tely", SearchOption.AllDirectories))
            .Select(File.ReadAllText));

        //Act
        List<string> notIncluded = fragments
            .Where(name => !sources.Contains(
                "@include " + RenderPaths.GeneratedDirectoryName + "/" + name,
                StringComparison.Ordinal))
            .ToList();

        //Assert
        // Read off the corpus rather than remembered, and paired with the zero-Include gate:
        // eighteen include sites that all resolved, against a mirror that CorpusMirrorTests
        // proves holds none of the eighteen files, is what "the manual consumed the PORT's
        // output" means. internals.texi is the nineteenth and is nobody's include — it is a
        // manual in its own right.
        notIncluded.Should().BeEmpty();
        fragments.Count.Should().Be(18);
    }

    /// <summary>The engraver was asked for every snippet and failed none.</summary>
    [Fact]
    public void the_engraver_was_asked_for_every_snippet_and_failed_none()
    {
        //Arrange
        EngineSnippetRenderer snippets = _fixture.Snippets;
        SortedDictionary<string, int> baseline = WarningSummary.ReadBaseline(Path.Combine(
            ToolPaths.ExpectedWarningsDirectory, _fixture.Manual.Name + "-snippets.tsv"));

        //Act
        SortedDictionary<string, int> actual = Program.SnippetCountsOf(
            snippets, _fixture.Html.Result.Images.Count);

        //Assert
        // ⚠ ASKED AND FAILED, NEVER COMPLETION. The package catches a renderer that throws
        // and shows the snippet's source instead, so "the manual rendered" is compatible with
        // every engraving having failed. The baseline freezes what was asked for as well as
        // what came back, so a render that quietly stopped ASKING — a search path that
        // stopped resolving the appendices, say — fails here too.
        actual.Should().BeEquivalentTo(baseline, ReportFailures(snippets));
    }

    /// <summary>Every engraving reached the document as a picture.</summary>
    [Fact]
    public void every_engraving_reached_the_document_as_a_picture()
    {
        //Arrange
        IReadOnlyList<TexinfoImageReference> images = _fixture.Html.Result.Images;

        //Act
        int engraved = images.Count(image => image.IsGenerated);
        int named = images.Count - engraved;

        //Assert
        // The engraver's own count of pictures produced has to equal the document's count of
        // pictures placed, or something was engraved and then dropped on the way in.
        //
        // ⚠ AND THIS IS ALSO THE FENCE AGAINST ENGRAVING THE MANUAL TWICE. The fixture now
        // produces BOTH formats, and it does so from one Texinfo pass; rendering them
        // separately would engrave every snippet once per format, because the package's
        // coordinator dedupes only within a render. That failure cannot be seen in the
        // engraving baseline alone — re-freezing it would simply record the doubled numbers —
        // but it shows up HERE, because the count on the left is the DOCUMENT's and the count
        // on the right is the ENGRAVER's, and only the second one doubles.
        engraved.Should().Be(_fixture.Snippets.PageCount);

        // The remaining two are the manual's own @sourceimage pictures — Gonville_before and
        // Gonville_after, added to the mirror at this wave. ⚠ They were MISSED by decision
        // D49's image survey, which looked for @image and found only macro definitions:
        // @sourceimage expands to @image{pictures/...}, one level below where that
        // measurement stopped. The render's two Include warnings are what found them.
        named.Should().Be(2);
    }

    /// <summary>Every engraved picture is an svg file that exists.</summary>
    [Fact]
    public void every_engraved_picture_is_an_svg_file_that_exists()
    {
        //Arrange
        IReadOnlyList<TexinfoImageReference> images = _fixture.Html.Result.Images;

        //Act
        List<string> wrong = images
            .Where(image => image.IsGenerated)
            .Where(image => !File.Exists(image.SourcePath)
                || !string.Equals(Path.GetExtension(image.SourcePath), ".svg",
                    StringComparison.OrdinalIgnoreCase)
                || new FileInfo(image.SourcePath).Length == 0)
            .Select(image => image.SourcePath)
            .ToList();

        //Assert
        // A picture reference with the right name and no bytes behind it places into the
        // document as a broken image and warns about nothing.
        wrong.Should().BeEmpty();
    }

    /// <summary>The two source images are placed rather than shown as alternate text.</summary>
    [Fact]
    public void the_two_source_images_are_placed_rather_than_shown_as_alternate_text()
    {
        //Arrange
        IReadOnlyList<TexinfoImageReference> images = _fixture.Html.Result.Images;

        //Act
        List<string> placed = images
            .Where(image => !image.IsGenerated)
            .Select(image => Path.GetFileName(image.SourcePath))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToList();

        //Assert
        placed.Should().BeEquivalentTo(new[] { "Gonville_after.png", "Gonville_before.png" });
    }

    /// <summary>The seven music symbols reach the reader as engraved music not as text.</summary>
    [Fact]
    public void the_seven_music_symbols_reach_the_reader_as_engraved_music_not_as_text()
    {
        //Arrange
        string source = File.ReadAllText(
            Path.Combine(_fixture.GeneratedDirectory, "markup-commands.tely"));
        string html = _fixture.HtmlText;

        //Act
        List<string> missingFromSource = new List<string>();
        List<string> presentInHtml = new List<string>();
        foreach (string symbol in Symbols())
        {
            if (!source.Contains(symbol, StringComparison.Ordinal))
            {
                missingFromSource.Add(symbol);
            }

            if (html.Contains(symbol, StringComparison.Ordinal))
            {
                presentInHtml.Add(symbol);
            }
        }

        //Assert
        // All seven are in the port's own generated bytes...
        missingFromSource.Should().BeEmpty();

        // ...and NONE of them is in the rendered text, because every one is markup inside a
        // @lilypond[quote] snippet rather than prose. Asserting the ABSENCE is the point: a
        // future change that put one of them in prose, or added `verbatim' to that snippet,
        // would put a character in front of a text renderer for the first time — and for the
        // PDF that is exactly the question decision D50 is open on. This gate is where such a
        // change announces itself.
        presentInHtml.Should().BeEmpty();

        // The snippet that draws them engraved: no failure was recorded against the file
        // they live in. Without this the gate above would also pass on a manual where that
        // snippet had silently failed and the symbols reached the reader as nothing at all.
        _fixture.Snippets.Failures
            .Where(failure => failure.Location.Contains("markup-commands.tely",
                StringComparison.Ordinal))
            .Should().BeEmpty();
    }

    private static IEnumerable<string> Symbols()
    {
        for (int i = 0; i < MusicSymbols.Length; i += char.IsSurrogatePair(MusicSymbols, i) ? 2 : 1)
        {
            yield return MusicSymbols.Substring(i,
                char.IsSurrogatePair(MusicSymbols, i) ? 2 : 1);
        }
    }

    /// <summary>The engraved music is cropped rather than left on full pages.</summary>
    [Fact]
    public void the_engraved_music_is_cropped_rather_than_left_on_full_pages()
    {
        //Arrange
        List<string> tall = new List<string>();
        List<TexinfoImageReference> sample = _fixture.Html.Result.Images
            .Where(image => image.IsGenerated).Take(200).ToList();

        //Act
        foreach (TexinfoImageReference image in sample)
        {
            Match height = Regex.Match(ReadHead(image.SourcePath, 512), @"height=""([0-9.]+)mm""");
            if (!height.Success
                || double.Parse(height.Groups[1].Value,
                    System.Globalization.CultureInfo.InvariantCulture) > 290)
            {
                tall.Add(image.SourcePath);
            }
        }

        //Assert
        // A4 is 297mm tall. An engraving left on a whole page would place into the manual as
        // a band of whitespace with a line of music at the top of it, and nothing else in
        // this suite would notice — the picture exists, the file has bytes, the count is
        // right. This is the gate on the ly:one-page-breaking directive that wave LD2 added.
        tall.Should().BeEmpty();
        sample.Count.Should().Be(200);
    }

    private static string ReadHead(string path, int count)
    {
        using FileStream stream = File.OpenRead(path);
        byte[] buffer = new byte[count];
        int read = stream.Read(buffer, 0, count);
        return Encoding.UTF8.GetString(buffer, 0, read);
    }

    private static string Report(IReadOnlyList<string> warnings)
        => string.Join("\n", warnings);

    private static string ReportFailures(EngineSnippetRenderer snippets)
    {
        StringBuilder builder = new StringBuilder();
        builder.Append(snippets.FailureCount).Append(" failure(s), ")
            .Append(snippets.DeclineCount).Append(" decline(s):");
        foreach (SnippetFailure failure in snippets.Failures.Take(20))
        {
            builder.Append('\n').Append(failure);
        }

        foreach (string decline in snippets.Declines.Take(20))
        {
            builder.Append('\n').Append(decline);
        }

        return builder.ToString();
    }

    /// <summary>Pdf facts match the frozen baseline exactly.</summary>
    [Fact]
    public void pdf_facts_match_the_frozen_baseline_exactly()
    {
        //Arrange
        string baselinePath = Path.Combine(
            ToolPaths.ExpectedWarningsDirectory, _fixture.Manual.Name + "-pdf.tsv");
        SortedDictionary<string, string> expected =
            WarningSummary.ReadPdfBaselineValues(baselinePath);

        //Act
        SortedDictionary<string, string> actual = _fixture.Pdf.BaselineValues();

        //Assert
        // Page count, warning counts, the page size actually used and the two shipped
        // defaults this wave deliberately left alone — asserted together and in both
        // directions. Freezing the SETTINGS beside the results is what keeps a page count
        // that moved from having two candidate explanations: if the size row still says A4
        // and the page count changed, the layout changed.
        actual.Should().BeEquivalentTo(expected, ReportPdf(_fixture.Pdf));
    }

    /// <summary>Pdf drops match the frozen baseline per code point.</summary>
    [Fact]
    public void pdf_drops_match_the_frozen_baseline_per_code_point()
    {
        //Arrange
        string baselinePath = Path.Combine(
            ToolPaths.ExpectedWarningsDirectory, _fixture.Manual.Name + "-pdf.tsv");
        List<string> expected = WarningSummary.ReadPdfBaselineDrops(baselinePath);

        //Act
        List<string> actual = _fixture.Pdf.DropRows();

        //Assert
        // ⚠ PER CODE POINT, NOT A TOTAL. Decision D47 tolerates coverage gaps, but tolerating
        // them is not the same as not knowing what they are: a total would go on passing
        // while a different character started dropping and an old one stopped. Each row
        // carries the warning's stable code, the code point and an exact occurrence count,
        // which is the surface TexinfoPdfWarnings.PdfItems was added to give this gate.
        actual.Should().BeEquivalentTo(expected, ReportPdf(_fixture.Pdf));
    }

    /// <summary>Every page of the pdf is a4.</summary>
    [Fact]
    public void every_page_of_the_pdf_is_a4()
    {
        //Arrange
        SortedSet<string> sizes = PdfPageBoxes.DistinctPageSizes(_fixture.PdfBytes);

        //Act
        int pagesMeasured = PdfPageBoxes.ReadMediaBoxes(_fixture.PdfBytes).Count;

        //Assert
        // ⚠ ASKED OF THE FILE, NOT OF THE OPTIONS. The manual declares @afourpaper and its
        // music was engraved to the 160 mm line width that declaration implies, so a US
        // Letter page would carry A4-measure music and look entirely plausible. Reading the
        // boxes back out of the bytes is the only form of this check that could ever fail.
        pagesMeasured.Should().Be(_fixture.Pdf.PageCount);
        sizes.Should().BeEquivalentTo(new SortedSet<string>(StringComparer.Ordinal) { "595x842" });
    }

    /// <summary>No picture was skipped by the pdf stage.</summary>
    [Fact]
    public void no_picture_was_skipped_by_the_pdf_stage()
    {
        //Arrange
        IReadOnlyList<RenderWarning> items = _fixture.Pdf.PdfItems;

        //Act
        List<string> imageWarnings = items
            .Where(item => item.Code != null
                && item.Code.StartsWith("image.", StringComparison.Ordinal))
            .Select(item => item.Code + " x" + item.Occurrences + ": " + item.Message)
            .ToList();

        //Assert
        // ⚠ THIS IS DECISION D51'S WHOLE RULING, AS A GATE. Until Html2Pdf gained SVG
        // placement it answered an SVG with "not in a supported format and was skipped" and
        // carried on, producing a complete music manual containing no music. Two and a half
        // thousand of those would have been two and a half thousand warnings and a green
        // page count.
        imageWarnings.Should().BeEmpty();
    }

    /// <summary>The pdf embeds a raster for every picture the document places.</summary>
    [Fact]
    public void the_pdf_embeds_a_raster_for_every_picture_the_document_places()
    {
        //Arrange
        string text = Encoding.Latin1.GetString(_fixture.PdfBytes);

        //Act
        int embedded = Regex.Matches(text, @"/Subtype\s*/Image").Count;

        //Assert
        // ⚠ COUNTED IN THE FILE, because "nothing warned" is not evidence that anything
        // arrived — and a music manual containing no music is precisely the artefact the old
        // Html2Pdf produced when handed an SVG.
        //
        // ⚠ A LOWER BOUND ON PURPOSE, and the bound is the honest part. Html2Pdf rasterizes
        // each SVG through Skia and embeds the result, but how many XObjects that costs is
        // the writer's business, not ours: MEASURED at wave LD4, one engraved picture also
        // brings a soft mask, and the count in the file is neither the picture count nor a
        // fixed multiple of it. Freezing a number whose structure this repository cannot
        // explain would be a baseline that fails for reasons nobody could read. What IS
        // knowable is that a document placing N pictures cannot be correct with fewer than N
        // rasters in it, and that is what this asserts.
        embedded.Should().BeGreaterThanOrEqualTo(_fixture.Html.Result.Images.Count);
    }

    private static string ReportPdf(ManualPdfRender pdf)
    {
        StringBuilder report = new StringBuilder();
        report.Append("pdf: ").Append(pdf.PageCount).Append(" pages, ")
            .Append(pdf.PdfWarnings.Count).Append(" warnings, ")
            .Append(pdf.PdfItems.Count).Append(" structured items");
        foreach (string row in pdf.DropRows())
        {
            report.Append('\n').Append("  ").Append(row.Replace('\t', ' '));
        }

        return report.ToString();
    }

}
