%% Generated by lilypond-book
%% Options: [exampleindent=10.16\mm,indent=0\mm,line-width=160\mm,paper-height=5\cm,paper-width=597.508\pt,papersize='(cons (* 597.508 pt) (* 5 cm))]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)



\paper {
  #(set-paper-size '(cons (* 597.508 pt) (* 5 cm)))
  indent = 0\mm
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 144
{ a'4 b'4 c'4 d'4 }


% ****************************************************************
% end ly snippet
% ****************************************************************
