%% Generated by lilypond-book
%% Options: [exampleindent=10.16\mm,fragment,indent=0\mm,line-width=160\mm,paper-height=845.047\pt,paper-width=597.508\pt,papersize='(cons (* 597.508 pt) (* 845.047 pt)),relative=-1]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)



\paper {
  #(set-paper-size '(cons (* 597.508 pt) (* 845.047 pt)))
  indent = 0\mm
  line-width = 160\mm
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}


\relative c,
{


% ****************************************************************
% ly snippet contents follows:
% ****************************************************************
\sourcefileline 46
a4 b4


% ****************************************************************
% end ly snippet
% ****************************************************************
}
