/*
  This file is part of LilyPond, the GNU music typesetter.

  Copyright (C) 1998--2026 Jan Nieuwenhuizen <janneke@gnu.org>
  Han-Wen Nienhuys

  LilyPond is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  LilyPond is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with LilyPond.  If not, see <http://www.gnu.org/licenses/>.
*/

using System.Collections.Generic;
using CodeBrix.LilyPort.Engine.Bootstrap;
using CodeBrix.LilyPort.Engine.Layout;
using CodeBrix.LilyPort.Flower;
using CodeBrix.LilyScheme.Values;

namespace CodeBrix.LilyPort.Engine.Objects; //was previously: lily/lyric-extender.cc, lily/include/lyric-extender.hh;

// Modified by Jeremy Ellis on 2026-08-07 as part of the CodeBrix port:
//   - upstream calls the Scheme predicate Lily::unbroken_spanner_p. That procedure is
//     (eq? spanner (ly:grob-original spanner)) and nothing else, and ly:grob-original
//     answers the grob itself when it has no original, so the port tests Original
//     directly rather than crossing into Scheme for a pointer comparison.

/*
  Extenders may be entered manually using __, or they can be
  auto-generated when autoExtenders = ##t.

  In autoExtenders mode, any Lyric syllable gets an extender
  if the associated voice is inside a melisma and the syllable
  is not followed by a hyphen.  This causes too many extenders
  to be created, which then have to be reduced by a minimum
  lengh requirement.

  Note: the extender is only used for one-syllable words, or
  for on a word's last syllable.  The extender should be aligned
  with the left side of the last note of the melisma, and not
  extend beond, lasting the whole duration of the melisma.
*/

/// <summary>
/// The line at the lyric baseline that shows how far a melisma runs.
/// <para>
/// Its right edge is decided by a stack of competing limits rather than by one rule: the
/// minimum length grows it, the system's right bound and the next syllable's left edge cut
/// it back, and the last note head it covers pushes it out again. An auto-generated
/// extender that ends up shorter than the note head it belongs to KILLS ITSELF, which is
/// how <c>autoExtenders</c> avoids littering the score with stubs.
/// </para>
/// </summary>
public static class LyricExtender
{
    private static readonly Symbol AutoGeneratedSymbol = Symbol.Intern("auto-generated");
    private static readonly Symbol HeadsSymbol = Symbol.Intern("heads");
    private static readonly Symbol LeftPaddingSymbol = Symbol.Intern("left-padding");
    private static readonly Symbol LineThicknessSymbol = Symbol.Intern("line-thickness");
    private static readonly Symbol LyricSyllableInterfaceSymbol
        = Symbol.Intern("lyric-syllable-interface");

    private static readonly Symbol MinimumLengthSymbol = Symbol.Intern("minimum-length");
    private static readonly Symbol NextSymbol = Symbol.Intern("next");
    private static readonly Symbol RemoveShortAutoextenderSymbol
        = Symbol.Intern("remove-short-autoextender");

    private static readonly Symbol RightPaddingSymbol = Symbol.Intern("right-padding");
    private static readonly Symbol ThicknessSymbol = Symbol.Intern("thickness");

    /// <summary>The <c>stencil</c> callback: a rounded box from the syllable to the last
    /// note head of the melisma.</summary>
    /// <param name="me">The extender spanner.</param>
    /// <returns>The stencil, or the empty list when the extender draws nothing.</returns>
    public static object Print(Spanner me)
    {
        Item leftEdge = me.GetBound(Direction.Negative);
        Item rightText = me.GetObject(NextSymbol) as Item;

        Grob common = leftEdge;

        if (rightText != null)
        {
            common = common.CommonRefpoint(rightText, Axis.X);
        }

        common = common.CommonRefpoint(me.GetBound(Direction.Positive), Axis.X);
        common = common.CommonRefpoint(me.GetSystem(), Axis.X);

        double sl = me.Layout == null ? 0.0 : me.Layout.GetDimension(LineThicknessSymbol);

        IReadOnlyList<Grob> heads = PointerGroupInterface.ExtractGrobSet(me, HeadsSymbol);

        if (heads.Count == 0)
        {
            return Nil.Instance;
        }

        common = AxisGroupInterface.CommonRefpointOfArray(heads, common, Axis.X);

        double leftPoint;
        if (leftEdge.HasInterface(LyricSyllableInterfaceSymbol))
        {
            leftPoint = leftEdge.Extent(common, Axis.X)[Direction.Positive];
        }
        else if (heads.Count > 0)
        {
            leftPoint = heads[0].Extent(common, Axis.X)[Direction.Negative];
        }
        else
        {
            leftPoint = leftEdge.Extent(common, Axis.X)[Direction.Positive];
        }

        if (double.IsInfinity(leftPoint))
        {
            return Nil.Instance;
        }

        /* It seems that short extenders are even lengthened to go past the
           note head, but haven't found a pattern in it yet. --hwn 1/1/04  */
        object minlen = me.GetProperty(MinimumLengthSymbol);
        double rightPoint = leftPoint + RobustDouble(minlen, 0.0);

        {
            Item rb = me.GetSystem()?.GetBound(Direction.Positive);
            if (rb != null)
            {
                double limit = rb.RelativeCoordinate(common, Axis.X);
                rightPoint = System.Math.Min(rightPoint, limit);
            }
        }

        if (heads.Count > 0)
        {
            double limit = heads[heads.Count - 1].Extent(common, Axis.X)[Direction.Positive];
            rightPoint = System.Math.Max(rightPoint, limit);
        }

        double h = sl * RobustDouble(me.GetProperty(ThicknessSymbol), 0.0);
        DrulArray<double> paddings = new DrulArray<double>(
            RobustDouble(me.GetProperty(LeftPaddingSymbol), h),
            RobustDouble(me.GetProperty(RightPaddingSymbol), h));

        if (rightText != null)
        {
            double limit = LooseColumns.RobustRelativeExtent(rightText, common, Axis.X)
                    [Direction.Negative]
                - paddings[Direction.Positive];

            rightPoint = System.Math.Min(rightPoint, limit);
        }

        /* run to end of line. */
        {
            Item rb = me.GetBound(Direction.Positive);
            if (rb != null && rb.BreakStatusDirection() != Direction.Center)
            {
                double limit = LooseColumns.RobustRelativeExtent(rb, common, Axis.X)
                        [Direction.Negative]
                    - paddings[Direction.Positive];

                rightPoint = System.Math.Max(rightPoint, limit);
            }
        }

        leftPoint += paddings[Direction.Negative];
        double w = rightPoint - leftPoint;

        if (w < 1.5 * h)
        {
            return Nil.Instance;
        }

        if (heads.Count > 0
            && me.Original == null
            && SchemeUtilities.ToBool(me.GetProperty(AutoGeneratedSymbol))
            && SchemeUtilities.ToBool(me.GetProperty(RemoveShortAutoextenderSymbol)))
        {
            double lastNoteheadX = heads[heads.Count - 1].Extent(common, Axis.X)
                [Direction.Negative];

            if (lastNoteheadX < leftPoint)
            {
                me.Suicide();
                return Nil.Instance;
            }
        }

        Stencil mol = Lookup.RoundFilledBox(
            new Box(new Interval(0, w), new Interval(0, h)), 0.8 * h);

        mol.TranslateAxis(leftPoint - me.RelativeCoordinate(common, Axis.X), Axis.X);
        return mol;
    }

    private static double RobustDouble(object value, double fallback)
        => SchemeConvert.IsNumber(value)
            ? SchemeConvert.ToDouble(value, "lyric extender")
            : fallback;
}
