#!/usr/bin/env python3
# Copyright (c) 2026 Jeremy Ellis and contributors
#
# Fresco.Brix is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""Generates Editor/CharsetTables.g.cs.

A hyphenation dictionary names its own character set on its first line, and
upstream's hyphenator hands that name to `codecs.getreader()' -- Python's
codec registry answers for every legacy single-byte set.  .NET's built-in set
is much smaller: outside UTF-* and ASCII only Latin-1 is there, so
ISO8859-2, ISO8859-7, KOI8-R and KOI8-U -- all four named by dictionaries
Fresco.Brix ships -- would be unreadable.

Rather than take a dependency on System.Text.Encoding.CodePages for four
lookup tables, this tool writes the tables themselves, read out of the same
codec registry upstream's reader uses.  Only the high half (0x80-0xFF) is
recorded: every set here is ASCII below that.

Run from anywhere:  python3 tools/charsettables/gen-charset-tables.py
"""

import os
import sys

# The sets the shipped dictionaries name, plus the ones a dictionary found in
# /usr/share/hyphen is most likely to name.  Each entry is (dic name, python
# codec); the dic name is what appears on a dictionary's first line.
CHARSETS = [
    ("ISO8859-1",  "iso8859_1"),
    ("ISO8859-2",  "iso8859_2"),
    ("ISO8859-3",  "iso8859_3"),
    ("ISO8859-4",  "iso8859_4"),
    ("ISO8859-5",  "iso8859_5"),
    ("ISO8859-6",  "iso8859_6"),
    ("ISO8859-7",  "iso8859_7"),
    ("ISO8859-8",  "iso8859_8"),
    ("ISO8859-9",  "iso8859_9"),
    ("ISO8859-10", "iso8859_10"),
    ("ISO8859-13", "iso8859_13"),
    ("ISO8859-14", "iso8859_14"),
    ("ISO8859-15", "iso8859_15"),
    ("ISO8859-16", "iso8859_16"),
    ("KOI8-R",     "koi8_r"),
    ("KOI8-U",     "koi8_u"),
    ("CP1250",     "cp1250"),
    ("CP1251",     "cp1251"),
    ("CP1252",     "cp1252"),
    ("CP1253",     "cp1253"),
    ("CP1257",     "cp1257"),
]

HEADER = """// Copyright (c) 2026 Jeremy Ellis and contributors
//
// Fresco.Brix is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// <auto-generated>
//     GENERATED FILE - do not edit by hand.
//     Written by tools/charsettables/gen-charset-tables.py from Python's own
//     codec registry, which is the registry upstream's hyphenator reads its
//     dictionaries through.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Fresco.Brix.Editor;

/// <summary>
/// The single-byte character sets a hyphenation dictionary may name on its
/// first line, as decoding tables for the high half of the byte range.
/// </summary>
/// <remarks>
/// <para>
/// .NET carries Latin-1 and the Unicode encodings and nothing else; a
/// dictionary that names ISO8859-2, ISO8859-7, KOI8-R or KOI8-U -- and four
/// of the dictionaries this application bundles do -- would otherwise be
/// read as mojibake or not at all. The tables are generated rather than
/// hand-written; see the tool named above.
/// </para>
/// <para>
/// Every set here agrees with ASCII below <c>0x80</c>, so only the 128 code
/// points from <c>0x80</c> up are recorded. A byte with no character in its
/// set is written as U+FFFD, which is what Python's <c>replace</c> handler
/// and .NET's decoder fallback both produce.
/// </para>
/// </remarks>
public static class CharsetTables
{
"""


def escape(ch):
    code = ord(ch)
    if code == 0xFFFD:
        return "\\ufffd"
    if ch == "\\":
        return "\\\\"
    if ch == '"':
        return '\\"'
    if 0x20 <= code < 0x7F:
        return ch
    return "\\u%04x" % code


def high_half(codec):
    """Returns the 128 characters bytes 0x80-0xFF decode to."""
    out = []
    for byte in range(0x80, 0x100):
        try:
            out.append(bytes([byte]).decode(codec))
        except UnicodeDecodeError:
            out.append("�")
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.normpath(os.path.join(
        here, "..", "..", "src", "Fresco.Brix.Core", "Editor", "CharsetTables.g.cs"))

    lines = [HEADER]
    lines.append("    private static readonly Dictionary<string, string> Tables\n")
    lines.append("        = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)\n")
    lines.append("    {\n")
    for name, codec in CHARSETS:
        table = "".join(escape(c) for c in high_half(codec))
        # Split the 128 characters over readable lines.
        lines.append('        ["%s"] =\n' % name)
        chunk = []
        width = 0
        pieces = [escape(c) for c in high_half(codec)]
        rows = []
        for piece in pieces:
            if width + len(piece) > 60:
                rows.append("".join(chunk))
                chunk, width = [], 0
            chunk.append(piece)
            width += len(piece)
        if chunk:
            rows.append("".join(chunk))
        for index, row in enumerate(rows):
            end = "," if index == len(rows) - 1 else ""
            joiner = "" if index == 0 else "+ "
            lines.append('            %s"%s"%s\n' % (joiner, row, end))
    lines.append("    };\n\n")

    lines.append("""    /// <summary>Gets the decoding table for a named character set.</summary>
    /// <param name="name">The name as a dictionary spells it on its first line.</param>
    /// <param name="table">The 128 characters bytes 0x80-0xFF stand for.</param>
    /// <returns>Whether the name is one of the sets recorded here.</returns>
    public static bool TryGetTable(string name, out string table)
    {
        if (string.IsNullOrEmpty(name))
        {
            table = null;
            return false;
        }

        return Tables.TryGetValue(name, out table);
    }

    /// <summary>Gets the names this class answers for.</summary>
    public static IReadOnlyCollection<string> Names => Tables.Keys;
}
""")

    with open(target, "w", encoding="utf-8") as handle:
        handle.write("".join(lines))
    print("wrote %s (%d charsets)" % (target, len(CHARSETS)))


if __name__ == "__main__":
    sys.exit(main())
