// Copyright (c) 2026 Jeremy Ellis and contributors
//
// CodeBrix.LilyPort is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using CodeBrix.LilyPort.Engine.Bootstrap;
using CodeBrix.LilyPort.Parsing.Grammar;

namespace CodeBrix.LilyPort.Parsing.Actions;

/// <summary>
/// One rule as the action porting effort tracks it.
/// </summary>
public sealed class ManifestEntry
{
    /// <summary>Initializes an entry.</summary>
    /// <param name="identity">The rule's stable identity.</param>
    /// <param name="hasAction">Whether upstream gives the rule an action body.</param>
    /// <param name="line">The line in <c>parser.yy</c> the rule starts on.</param>
    public ManifestEntry(string identity, bool hasAction, int line)
    {
        Identity = identity;
        HasAction = hasAction;
        Line = line;
    }

    /// <summary>Gets the rule's stable identity — the production written out.</summary>
    public string Identity { get; }

    /// <summary>Gets a value indicating whether upstream gives this rule an action body.</summary>
    public bool HasAction { get; }

    /// <summary>Gets the line in <c>parser.yy</c> the rule starts on.</summary>
    public int Line { get; }

    /// <summary>Returns the external representation.</summary>
    /// <returns>The identity.</returns>
    public override string ToString() => Identity;
}

/// <summary>
/// The list of every rule in the vendored grammar, and which of them have an action
/// body to hand-port.
/// <para>
/// Decision O7 promises this: "the generator emits a manifest; a fence test asserts
/// every rule is implemented or on a recorded not-yet list". The manifest is COMMITTED
/// DATA — <c>Actions/rule-manifest.tsv</c> — regenerated only when the grammar mirror
/// is deliberately re-synced. Its job is to make a re-sync's effect on the porting
/// effort visible: a rule that appeared, vanished or changed shape shows up as a diff
/// in one file rather than as a silently unreachable action.
/// </para>
/// <para>
/// Rules are keyed by IDENTITY rather than by index for the reason recorded in
/// <see cref="BisonGrammarReader"/>: an index shifts the moment anything is inserted
/// above it, so a re-sync adding one rule near the top would appear to change every
/// action below it.
/// </para>
/// </summary>
public static class RuleManifest
{
    private const string ResourceName = "rule-manifest.tsv";

    private static IReadOnlyList<ManifestEntry> _entries;

    /// <summary>Gets the manifest, read from the embedded data file.</summary>
    public static IReadOnlyList<ManifestEntry> Entries => _entries ??= Read();

    /// <summary>Gets the identities of the rules that carry an action body.</summary>
    public static IReadOnlyList<string> WithActions
    {
        get
        {
            List<string> identities = new List<string>();
            foreach (ManifestEntry entry in Entries)
            {
                if (entry.HasAction)
                {
                    identities.Add(entry.Identity);
                }
            }

            return identities;
        }
    }

    /// <summary>
    /// Renders a manifest from a grammar, in the committed file's format.
    /// </summary>
    /// <param name="grammar">The grammar to render.</param>
    /// <returns>The manifest text.</returns>
    public static string Render(BisonGrammar grammar)
    {
        if (grammar == null)
        {
            throw new ArgumentNullException(nameof(grammar));
        }

        StringBuilder text = new StringBuilder();
        // The pin is read from the engine's one declaration rather than written here as a
        // literal, so a re-sync onto a newer LilyPond stamps the regenerated manifest with
        // the release it was actually generated from.
        text.Append("# Every production in the vendored lily/parser.yy, at the v"
            + LilyVersion.CompatibleWithVersion + " pin.\n");
        text.Append("# Generated by RuleManifest.Render; committed data, regenerated only on a\n");
        text.Append("# deliberate re-sync of parser-mirror/. See Actions/RuleManifest.cs.\n");
        text.Append("#\n");
        text.Append("# has-action<TAB>parser.yy-line<TAB>rule-identity\n");

        foreach (GrammarRule rule in grammar.Rules)
        {
            text.Append(rule.ActionText != null ? "action" : "-");
            text.Append('\t');
            text.Append(rule.Line.ToString(CultureInfo.InvariantCulture));
            text.Append('\t');
            text.Append(rule.Identity);
            text.Append('\n');
        }

        return text.ToString();
    }

    private static IReadOnlyList<ManifestEntry> Read()
    {
        Assembly assembly = typeof(RuleManifest).Assembly;
        string resource = assembly.GetManifestResourceNames()
            .FirstOrDefault(name => name.EndsWith("." + ResourceName, StringComparison.Ordinal));

        if (resource == null)
        {
            throw new InvalidOperationException(
                "The embedded '" + ResourceName + "' is missing from the assembly.");
        }

        List<ManifestEntry> entries = new List<ManifestEntry>();

        using Stream stream = assembly.GetManifestResourceStream(resource);
        using StreamReader reader = new StreamReader(stream);

        string line;
        while ((line = reader.ReadLine()) != null)
        {
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            string[] parts = line.Split('\t');
            if (parts.Length < 3)
            {
                continue;
            }

            entries.Add(new ManifestEntry(
                parts[2],
                string.Equals(parts[0], "action", StringComparison.Ordinal),
                int.Parse(parts[1], NumberStyles.Integer, CultureInfo.InvariantCulture)));
        }

        return entries;
    }
}
