#!/bin/bash
#
# generate-midi-reference.sh -- run the official LilyPond binary over the MIDI
#                               regression subsuite and record the .midi it produces.
#
# This file is part of CodeBrix.LilyPort.
# Copyright (c) 2026 Jeremy Ellis and contributors
#
# CodeBrix.LilyPort is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ----------------------------------------------------------------------------
# WHY THIS IS SEPARATE FROM generate-reference.sh
#
# The layout oracle renders 2,146 files with --formats=svg and stores 62 MB of
# pages. MIDI is a different subsuite (tests/regression/midi, 73 files), a
# different output format, and a different comparator -- and, unlike the pages,
# the .midi files are SMALL. The whole reference is well under a megabyte, so it
# is committed rather than regenerated, and the manifest exists to prove it has
# not drifted.
#
# The naming convention is upstream's, from scm/midi.scm's write-performances-midis:
# the first performance in a file is <base>.midi and any further ones are
# <base>-<n>.midi counting from 1. compare-midi.py pairs candidate to reference by
# that name alone, so the port's BatchRunner reproduces it exactly.
# ----------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LILYPORT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SUITE_DIR="${LILYPORT_ROOT}/tests/regression/midi"

LILYPOND_BIN="${LILYPOND_BIN:-}"
OUT_DIR="${1:-${SCRIPT_DIR}/reference-midi}"
JOBS="${JOBS:-$(nproc)}"
PER_FILE_TIMEOUT="${PER_FILE_TIMEOUT:-60}"

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
note() { printf '    %s\n' "$*"; }
die() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

say "Preflight"

if [ -z "${LILYPOND_BIN}" ]; then
    if command -v lilypond >/dev/null 2>&1; then
        LILYPOND_BIN="$(command -v lilypond)"
    else
        die "lilypond not found. Extract the official release and set LILYPOND_BIN, e.g.
    export LILYPOND_BIN=\$HOME/ClaudeHome/oracle/lilypond-2.27.2/bin/lilypond"
    fi
fi

[ -x "${LILYPOND_BIN}" ] || die "not executable: ${LILYPOND_BIN}"
[ -d "${SUITE_DIR}" ] || die "MIDI subsuite not found at ${SUITE_DIR}"

VERSION="$("${LILYPOND_BIN}" --version 2>&1 | head -1)"
note "oracle:  ${LILYPOND_BIN}"
note "         ${VERSION}"
note "suite:   ${SUITE_DIR} ($(ls "${SUITE_DIR}"/*.ly 2>/dev/null | wc -l) files)"
note "output:  ${OUT_DIR}"

case "${VERSION}" in
    *2.27.2*) ;;
    *) note "WARNING: the port targets 2.27.2. Comparing against a different"
       note "         version measures version drift, not port fidelity." ;;
esac

mkdir -p "${OUT_DIR}/midi" "${OUT_DIR}/logs"

WORKER="${OUT_DIR}/.render-one-midi.sh"
cat > "${WORKER}" <<'WORKER_EOF'
#!/bin/bash
set -uo pipefail
ly="$1"; out_dir="$2"; lilypond="$3"; timeout_s="$4"
name="$(basename "${ly}" .ly)"
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

# --formats=midi asks for MIDI and nothing else: no pages are rendered, which is
# what makes this run fast enough to be worth having as its own step.
if timeout "${timeout_s}" "${lilypond}" \
        --formats=midi -dno-point-and-click --silent \
        -o "${work}/${name}" "${ly}" > "${out_dir}/logs/${name}.log" 2>&1; then
    produced=0
    for midi in "${work}/${name}"*.midi; do
        [ -e "${midi}" ] || continue
        cp "${midi}" "${out_dir}/midi/$(basename "${midi}")"
        produced=1
    done
    [ "${produced}" = "1" ] && echo "OK ${name}" || echo "NOOUT ${name}"
else
    status=$?
    [ "${status}" = "124" ] && echo "TIMEOUT ${name}" || echo "FAIL ${name}"
fi
WORKER_EOF
chmod +x "${WORKER}"

say "Rendering"

FILES="$(ls "${SUITE_DIR}"/*.ly)"
TOTAL="$(echo "${FILES}" | wc -l)"
note "${TOTAL} file(s), ${PER_FILE_TIMEOUT}s timeout each"

echo "${FILES}" \
    | xargs -P "${JOBS}" -I@ "${WORKER}" @ "${OUT_DIR}" "${LILYPOND_BIN}" "${PER_FILE_TIMEOUT}" \
    > "${OUT_DIR}/render-status.txt" || true

OK="$(grep -c '^OK ' "${OUT_DIR}/render-status.txt" || true)"
FAILED="$(grep -c '^FAIL ' "${OUT_DIR}/render-status.txt" || true)"
NOOUT="$(grep -c '^NOOUT ' "${OUT_DIR}/render-status.txt" || true)"
TIMEDOUT="$(grep -c '^TIMEOUT ' "${OUT_DIR}/render-status.txt" || true)"

say "Building the manifest"

{
    echo "# CodeBrix.LilyPort MIDI reference manifest"
    echo "# Generated by tools/regression-harness/generate-midi-reference.sh"
    echo "# Oracle: ${VERSION}"
    echo "# Columns: sha256 <TAB> bytes <TAB> output-file"
} > "${OUT_DIR}/manifest.tsv"

(
    cd "${OUT_DIR}/midi"
    for f in *.midi; do
        [ -e "${f}" ] || continue
        printf '%s\t%s\t%s\n' "$(sha256sum "${f}" | cut -d' ' -f1)" "$(stat -c%s "${f}")" "${f}"
    done | sort -k3,3
) >> "${OUT_DIR}/manifest.tsv"

say "Done"
note "rendered ok : ${OK}"
note "no output   : ${NOOUT}   (input asks for no \\midi -- expected for a few)"
note "failed      : ${FAILED}"
note "timed out   : ${TIMEDOUT}"
note "manifest    : ${OUT_DIR}/manifest.tsv ($(grep -vc '^#' "${OUT_DIR}/manifest.tsv") entries)"
note "midi output : ${OUT_DIR}/midi ($(du -sh "${OUT_DIR}/midi" | cut -f1))"
note ""
note "Next: python3 compare-midi.py reference-midi/midi candidate/midi"
