// Copyright (c) 2026 Jeremy Ellis and contributors
//
// CodeBrix.LilyPort is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Lily.Docs.Snippets;

/// <summary>
/// Composes the LilyPond source for one documentation snippet, the way lilypond-book
/// composes it.
/// <para>
/// Ported from <c>python/book_snippets.py:193-262</c> (the three templates and the
/// <c>snippet_options</c> template groups) and <c>:552-679</c> (<c>compose_ly</c>), read
/// in <c>book-mirror/</c> at committish
/// <c>2d621459bd44cb1758f822a69757242eab843060</c>.
/// </para>
/// <para>
/// ⚠ THE TEMPLATES ARE PYTHON <c>%</c>-FORMAT STRINGS AND THE ESCAPES ARE LOAD-BEARING.
/// A <c>%%</c> in a template becomes ONE <c>%</c> in the output, so the file's banner
/// comments arrive as <c>%%&#160;Generated by lilypond-book</c> (from <c>%%%%</c>) and its
/// rules as <c>%&#160;****</c> (from <c>%%&#160;****</c>). Reduction happens ONCE per
/// formatting pass and substituted values are never rescanned, which matters because the
/// paper and layout blocks are formatted first and then substituted into the outer
/// template: a paper block's own <c>%%</c> has already become <c>%</c> by then and does
/// not reduce again. <see cref="Format"/> reproduces exactly that, and
/// <c>ComposerTemplateTests</c> fences it against the oracle's own output.
/// </para>
/// </summary>
public sealed class LilypondSourceComposer
{
    private const string Rule =
        "****************************************************************";

    /// <summary><c>book_snippets.py:193-215</c>, verbatim.</summary>
    private const string PreambleTemplate =
        "%%%% Generated by lilypond-book\n"
        + "%%%% Options: [%(option_string)s]\n"
        + "\\include \"lilypond-book-preamble.ly\"\n"
        + "\n"
        + "\n"
        + "%% " + Rule + "\n"
        + "%% Start cut-&-pastable-section\n"
        + "%% " + Rule + "\n"
        + "\n"
        + "%(padding_mm_string)s\n"
        + "\n"
        + "%(preamble_string)s\n"
        + "\n"
        + "\\paper {\n"
        + "  %(paper_string)s\n"
        + "}\n"
        + "\n"
        + "\\layout {\n"
        + "  %(layout_string)s\n"
        + "}\n"
        + "\n";

    /// <summary><c>book_snippets.py:217-229</c>, verbatim.</summary>
    private const string FullTemplate =
        "\n"
        + "\n"
        + "\n"
        + "%% " + Rule + "\n"
        + "%% ly snippet:\n"
        + "%% " + Rule + "\n"
        + "%(code)s\n"
        + "\n"
        + "\n"
        + "%% " + Rule + "\n"
        + "%% end ly snippet\n"
        + "%% " + Rule + "\n";

    /// <summary><c>book_snippets.py:231-246</c>, verbatim.</summary>
    private const string FragmentTemplate =
        "\n"
        + "%(notes_string)s\n"
        + "{\n"
        + "\n"
        + "\n"
        + "%% " + Rule + "\n"
        + "%% ly snippet contents follows:\n"
        + "%% " + Rule + "\n"
        + "%(code)s\n"
        + "\n"
        + "\n"
        + "%% " + Rule + "\n"
        + "%% end ly snippet\n"
        + "%% " + Rule + "\n"
        + "}\n";

    /// <summary>
    /// The default <c>--left-padding</c>, from <c>lilypond-book.py:187-193</c>.
    /// </summary>
    private const double DefaultPaddingMillimetres = 3.0;

    /// <summary>
    /// What an <c>inline</c> snippet's padding becomes: "value 0 would make LilyPond
    /// apply no left padding at all, but still apply some right padding", so upstream
    /// uses the smallest non-zero value instead (<c>book_snippets.py:644-657</c>).
    /// </summary>
    private const double InlinePaddingMillimetres = 0.0001;

    private static readonly Regex PlaceholderRegex = new Regex(
        @"%(?:%|\((?<name>[^)]+)\)(?<kind>[sf]))", RegexOptions.Compiled);

    /// <summary>The <c>NOTES</c> template group — <c>book_snippets.py:126-128</c>.</summary>
    private static readonly Dictionary<string, string> NotesTemplates =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { SnippetOptionNames.Relative, @"\relative c%(relative_quotes)s" },
        };

    /// <summary>The <c>PAPER</c> template group — <c>book_snippets.py:133-146</c>.</summary>
    private static readonly Dictionary<string, string> PaperTemplates =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { SnippetOptionNames.PaperSize, "#(set-paper-size %(papersize)s)" },
            { SnippetOptionNames.Indent, "indent = %(indent)s" },
            {
                SnippetOptionNames.LineWidth,
                "line-width = %(line-width)s\n"
                + "  %% offset the left padding, also add 1mm as lilypond creates cropped\n"
                + "  %% images with a little space on the right\n"
                + "  line-width = #(- line-width (* mm  %(padding_mm)f) (* mm 1))"
            },
            {
                SnippetOptionNames.Quote,
                "line-width = %(line-width)s - 2.0 * %(exampleindent)s\n"
                + "  %% offset the left padding, also add 1mm as lilypond creates cropped\n"
                + "  %% images with a little space on the right\n"
                + "  line-width = #(- line-width (* mm  %(padding_mm)f) (* mm 1))"
            },
            { SnippetOptionNames.RaggedRight, "ragged-right = ##t" },
            { SnippetOptionNames.NoRaggedRight, "ragged-right = ##f" },
        };

    /// <summary>The <c>LAYOUT</c> template group — <c>book_snippets.py:149-160</c>.</summary>
    private static readonly Dictionary<string, string> LayoutTemplates =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            {
                SnippetOptionNames.NoTime,
                "\n \\context {\n   \\Score\n   timing = ##f\n }\n"
                + " \\context {\n   \\Staff\n   \\remove Time_signature_engraver\n }"
            },
        };

    /// <summary>The <c>PREAMBLE</c> template group — <c>book_snippets.py:163-165</c>.</summary>
    private static readonly Dictionary<string, string> PreambleTemplates =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { SnippetOptionNames.StaffSize, "#(set-global-staff-size %(staffsize)s)" },
        };

    private readonly TexinfoPageGeometry _geometry;

    /// <summary>Creates a composer for one manual's page geometry.</summary>
    /// <param name="geometry">The manual's geometry.</param>
    public LilypondSourceComposer(TexinfoPageGeometry geometry)
    {
        _geometry = geometry ?? throw new ArgumentNullException(nameof(geometry));
    }

    /// <summary>
    /// Composes one snippet's source.
    /// </summary>
    /// <param name="code">The snippet's own music, as written in the manual.</param>
    /// <param name="writtenOptions">The snippet's bracketed options as written, i.e. the
    /// package's <c>Options.All</c>.</param>
    /// <param name="lineNumber">The line the snippet begins on in its manual, counting
    /// from one; written into the source as <c>\sourcefileline</c> so LilyPond's own
    /// diagnostics point back at the manual.</param>
    /// <returns>The composed source, and the option set it was composed from.</returns>
    public ComposedSnippet Compose(string code, IReadOnlyList<string> writtenOptions,
        int lineNumber)
    {
        if (code == null)
        {
            throw new ArgumentNullException(nameof(code));
        }

        return ComposeCore(SourceFileLine(code, lineNumber), writtenOptions);
    }

    /// <summary>
    /// Composes from music that already carries its position prologue, which is the only
    /// thing that differs between inline music and a named file.
    /// </summary>
    /// <param name="preparedCode">The music, prologue included.</param>
    /// <param name="writtenOptions">The snippet's bracketed options as written.</param>
    /// <returns>The composed source, and the option set it was composed from.</returns>
    private ComposedSnippet ComposeCore(string preparedCode,
        IReadOnlyList<string> writtenOptions)
    {
        SnippetOptionSet options = SnippetOptionSet.For(writtenOptions, _geometry);

        // ── `ignore_options': a snippet that sizes its own paper but not its line width
        // gets NEITHER the default width NOR the quote narrowing, "since it wouldn't give
        // good results, especially if the paper size is smaller".
        HashSet<string> ignored = new HashSet<string>(StringComparer.Ordinal);
        if (options.WasGivenExplicitly(SnippetOptionNames.PaperSize)
            && !options.WasGivenExplicitly(SnippetOptionNames.LineWidth))
        {
            ignored.Add(SnippetOptionNames.LineWidth);
            ignored.Add(SnippetOptionNames.Quote);
        }

        // ── `override': the fallback values a template may substitute, widened by the
        // format's own geometry. The two literals are upstream's own fallbacks and are
        // both overwritten by the geometry immediately; they matter only for a format
        // that supplies neither.
        Dictionary<string, string> substitutions =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { SnippetOptionNames.ExampleIndent, @"0.4\in" },
                { SnippetOptionNames.LineWidth, @"5\in" },
                { SnippetOptionNames.PaperHeight, _geometry.PaperHeight },
                { SnippetOptionNames.PaperWidth, _geometry.PaperWidth },
                { SnippetOptionNames.Alt, TexinfoPageGeometry.AltText },
            };
        substitutions[SnippetOptionNames.LineWidth] = _geometry.LineWidth;
        substitutions[SnippetOptionNames.ExampleIndent] = _geometry.ExampleIndent;

        List<string> notes = new List<string>();
        List<string> preamble = new List<string>();
        List<string> layout = new List<string>();
        List<string> paper = new List<string>();
        List<string> unknown = new List<string>();

        foreach (KeyValuePair<string, string> option in options.Effective)
        {
            if (ignored.Contains(option.Key))
            {
                continue;
            }

            if (!string.IsNullOrEmpty(option.Value))
            {
                substitutions[option.Key] = option.Value;
            }
            else if (!substitutions.ContainsKey(option.Key))
            {
                substitutions[option.Key] = null;
            }

            if (NotesTemplates.TryGetValue(option.Key, out string notesTemplate))
            {
                notes.Add(notesTemplate);
            }
            else if (PreambleTemplates.TryGetValue(option.Key, out string preambleTemplate))
            {
                preamble.Add(preambleTemplate);
            }
            else if (LayoutTemplates.TryGetValue(option.Key, out string layoutTemplate))
            {
                layout.Add(layoutTemplate);
            }
            else if (PaperTemplates.TryGetValue(option.Key, out string paperTemplate))
            {
                paper.Add(paperTemplate);
            }
            else if (!SnippetOptionSet.IsSimpleOption(option.Key))
            {
                // Upstream's "ignoring unknown ly option" warning. It is COLLECTED rather
                // than printed, because a docs render must be able to assert on it.
                unknown.Add(option.Key);
            }
        }

        // ── `\relative' quoting: 1 is central C, so a positive value is that many
        // apostrophes and a negative one that many commas.
        int relative = 1;
        if (substitutions.TryGetValue(SnippetOptionNames.Relative, out string relativeValue)
            && !string.IsNullOrEmpty(relativeValue)
            && int.TryParse(relativeValue, NumberStyles.Integer, CultureInfo.InvariantCulture,
                out int parsedRelative))
        {
            relative = parsedRelative;
        }

        string relativeQuotes = relative < 0
            ? new string(',', -relative)
            : relative > 0 ? new string('\'', relative) : string.Empty;

        double padding = substitutions.ContainsKey(SnippetOptionNames.Inline)
            ? InlinePaddingMillimetres
            : DefaultPaddingMillimetres;
        substitutions["padding_mm"] = padding.ToString("F6", CultureInfo.InvariantCulture);
        substitutions["relative_quotes"] = relativeQuotes;

        // ── "put paper-size first, if it exists" ─────────────────────────────────────
        for (int i = 0; i < paper.Count; i++)
        {
            if (paper[i].StartsWith("#(set-paper-size", StringComparison.Ordinal))
            {
                string first = paper[i];
                paper.RemoveAt(i);
                paper.Insert(0, first);
                break;
            }
        }

        string paperString = Format(string.Join("\n  ", paper), substitutions);
        string layoutString = Format(string.Join("\n  ", layout), substitutions);
        string notesString = Format(string.Join("\n  ", notes), substitutions);
        string preambleString = Format(string.Join("\n  ", preamble), substitutions);

        string paddingString = padding != 0
            ? "#(ly:set-option 'eps-box-padding "
                + padding.ToString("F6", CultureInfo.InvariantCulture) + ")"
            : string.Empty;

        Dictionary<string, string> outer =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "option_string", string.Join(",", options.OutputRelevant) },
                { "padding_mm_string", paddingString },
                { "preamble_string", preambleString },
                { "paper_string", paperString },
                { "layout_string", layoutString },
                { "notes_string", notesString },
                { "code", preparedCode },
            };

        string body = options.IsFragment ? FragmentTemplate : FullTemplate;
        string composed = Format(PreambleTemplate + body, outer);

        return new ComposedSnippet(composed, options, unknown);
    }

    /// <summary>
    /// Composes the source for an <c>@lilypondfile</c> — a snippet whose music is a whole
    /// file rather than text written in the manual.
    /// <para>
    /// Ported from <c>book_snippets.py:969-972</c> (<c>LilypondFileSnippet.ly</c>). The
    /// difference from inline music is only the position prologue: the file is named with
    /// <c>\sourcefilename</c> and its line count starts at zero, because the music did not
    /// come from the manual. Everything after that — the option set, the paper and layout
    /// blocks, the fragment-or-whole-file choice — is composed identically.
    /// </para>
    /// </summary>
    /// <param name="fileName">The file name as the manual wrote it, which is what goes
    /// into <c>\sourcefilename</c> — not the resolved path, so a diagnostic points at what
    /// the author typed.</param>
    /// <param name="contents">The file's whole text.</param>
    /// <param name="writtenOptions">The snippet's bracketed options as written.</param>
    /// <returns>The composed source, and the option set it was composed from.</returns>
    public ComposedSnippet ComposeFile(string fileName, string contents,
        IReadOnlyList<string> writtenOptions)
    {
        if (contents == null)
        {
            throw new ArgumentNullException(nameof(contents));
        }

        return ComposeCore(
            "\\sourcefilename \"" + (fileName ?? string.Empty) + "\"\n\\sourcefileline 0\n"
                + contents,
            writtenOptions);
    }

    /// <summary>
    /// Strips the lines lilypond-book itself disregards when it asks whether two composed
    /// sources are the same snippet — <c>book_snippets.py:725-726</c>'s
    /// <c>relevant_contents</c>.
    /// <para>
    /// This is the right basis for a parity diff against the oracle, and not merely a
    /// convenience: <c>\sourcefileline</c> records where a snippet sat in its manual, so
    /// two identical snippets in different places compose to different bytes. Upstream
    /// removes those lines before comparing for exactly that reason, so comparing what
    /// upstream compares is comparing the thing that means something.
    /// </para>
    /// </summary>
    /// <param name="composed">A composed source.</param>
    /// <returns>The source without its version and source-position lines.</returns>
    public static string RelevantContents(string composed)
    {
        if (composed == null)
        {
            return string.Empty;
        }

        return Regex.Replace(composed, @"\\(version|sourcefileline|sourcefilename)[^\n]*\n",
            string.Empty);
    }

    /// <summary>
    /// <c>book_snippets.py:416-421</c> — the snippet's music, preceded by the position it
    /// came from. Upstream writes <c>line_number - 1</c> because <c>\sourcefileline</c>
    /// names the line BEFORE the following text.
    /// </summary>
    private static string SourceFileLine(string code, int lineNumber)
        => "\\sourcefileline " + (lineNumber - 1).ToString(CultureInfo.InvariantCulture)
            + "\n" + code;

    /// <summary>
    /// Applies python's <c>%</c> formatting for the subset the templates use: <c>%%</c>
    /// for a literal percent, <c>%(name)s</c> for a string and <c>%(name)f</c> for a
    /// float already formatted to six places.
    /// </summary>
    /// <param name="template">The template text.</param>
    /// <param name="values">The substitution values.</param>
    /// <returns>The formatted text.</returns>
    /// <exception cref="InvalidOperationException">A template names a value that was not
    /// supplied — upstream's own <c>KeyError</c>, which must not become an empty string
    /// here: a silently blank paper block renders and looks plausible.</exception>
    internal static string Format(string template, IDictionary<string, string> values)
    {
        if (string.IsNullOrEmpty(template))
        {
            return string.Empty;
        }

        StringBuilder builder = new StringBuilder(template.Length);
        int position = 0;
        foreach (Match match in PlaceholderRegex.Matches(template))
        {
            builder.Append(template, position, match.Index - position);
            position = match.Index + match.Length;

            string name = match.Groups["name"].Value;
            if (string.IsNullOrEmpty(name))
            {
                builder.Append('%');
                continue;
            }

            if (!values.TryGetValue(name, out string value) || value == null)
            {
                throw new InvalidOperationException(
                    "the snippet template names '" + name + "', which the option set does "
                    + "not supply; composing it as blank would render and look plausible");
            }

            builder.Append(value);
        }

        builder.Append(template, position, template.Length - position);
        return builder.ToString();
    }
}

/// <summary>One snippet's composed source, and what it was composed from.</summary>
public sealed class ComposedSnippet
{
    internal ComposedSnippet(string source, SnippetOptionSet options,
        IReadOnlyList<string> unknownOptions)
    {
        Source = source;
        Options = options;
        UnknownOptions = unknownOptions;
    }

    /// <summary>The composed LilyPond source, ready to engrave.</summary>
    public string Source { get; }

    /// <summary>The effective option set it was composed from.</summary>
    public SnippetOptionSet Options { get; }

    /// <summary>
    /// Options that reached the composer with no template and no place in
    /// <c>simple_options</c> — upstream's "ignoring unknown ly option". Empty for every
    /// snippet in the corpus (measured); a non-empty list is a finding.
    /// </summary>
    public IReadOnlyList<string> UnknownOptions { get; }

    /// <summary>The source without the lines lilypond-book disregards when comparing.</summary>
    public string RelevantContents => LilypondSourceComposer.RelevantContents(Source);
}
