// === Python slexer (Stateful Lexer) module ===
//
// Copyright (c) 2008 - 2015 by Wilbert Berendsen
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
// See http://www.gnu.org/licenses/ for more information.

using System.Text.RegularExpressions;

namespace Fresco.Brix.Ly.Slexing; //was previously: ly/slexer.py (class FallthroughParser);

// Modified by Jeremy Ellis - 2026 - as part of the Fresco.Brix port.

/// <summary>
/// Base class for parsers that MATCH at the position instead of SEARCHING from it —
/// and that, on no match, leave themselves rather than stopping the tokenizer.
/// </summary>
public abstract class FallthroughParser : Parser
{
    /// <summary>Gets whether the pattern anchors at the position: it does.</summary>
    protected override bool Anchored => true;

    /// <summary>
    /// Matches text AT the position — Python's <c>re.match</c> — and returns the
    /// match or <see langword="null"/>.
    /// </summary>
    /// <param name="text">The text.</param>
    /// <param name="pos">The position the match must start at.</param>
    /// <returns>The match, or <see langword="null"/>.</returns>
    public override Match Parse(string text, int pos)
    {
        Match match = Pattern.Searcher.Match(text, pos);
        return match.Success && match.Index == pos ? match : null;
    }

    /// <summary>
    /// (Internal) Called by <see cref="State.Follow"/>: falls through if the token
    /// cannot have been generated by this parser — upstream tests
    /// <c>type(token) not in self.items</c>, a test on the token's EXACT class
    /// against the classes the items name.
    /// </summary>
    /// <param name="token">The token being followed.</param>
    /// <param name="state">The state following it.</param>
    /// <returns>Whether the state fell through.</returns>
    public override bool FollowInternal(Token token, State state)
    {
        System.Type tokenClass = token.GetType();
        foreach (TokenRule rule in ItemRules)
        {
            if (rule.TokenClass == tokenClass)
            {
                return false;
            }
        }

        Fallthrough(state);
        return true;
    }

    /// <summary>
    /// Called when no match is returned: leaves the current parser and answers
    /// <see langword="false"/> so the State continues parsing.
    /// </summary>
    /// <param name="state">The state to alter.</param>
    /// <returns><see langword="false"/> — parsing continues.</returns>
    public override bool Fallthrough(State state)
    {
        state.Leave();
        return false;
    }
}
